[package]
name = "Bridge"
version = "0.0.2"
published-at = "0x45b8ad80ead412878fdbffaadca2c675648e474c947242c2455875eb66f32de3"
edition = "2024.beta"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/testnet"

[dependencies.MoveStdlib]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/move-stdlib"
rev = "framework/testnet"

[dependencies.SuiSystem]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-system"
rev = "framework/testnet"

[addresses]
bridge = "0x0"

